# Generated by Django 5.0.8 on 2024-08-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
